import { getCardImage } from './imageMap';
import { CARD_DATA } from './cardData';
import type { CardDef } from './types';

// Maps card id → PNG filename in src/images/
const IMAGE_FILES: Record<number, string> = {
  1:  'acid_attacks.png',
  2:  'alien_origin.png',
  3:  'alpha_monster.png',
  4:  'apartment_building.png',
  5:  'armor_plating.png',
  6:  'background_dweller.png',
  7:  'burrowing.png',
  8:  'camouflage.png',
  9:  'commuter_train.png',
  10: 'complete_destruction.png',
  11: 'corner_store.png',
  12: 'media_friendly.png',
  13: 'death_from_above.png',
  14: 'eater_of_the_dead.png',
  15: 'energize.png',
  16: 'energy_hoarder.png',
  17: 'evacuation_orders.png',
  18: 'even_bigger.png',
  19: 'extra_head.png',
  20: 'flame_thrower.png',
  21: 'fire_breathing.png',
  22: 'freeze_time.png',
  23: 'frenzy.png',
  24: 'friend_of_children.png',
  25: 'gas_refinery.png',
  26: 'giant_brain.png',
  27: 'gourmet.png',
  28: 'heal.png',
  29: 'healing_ray.png',
  30: 'herbivore.png',
  31: 'hero_culler.png',
  32: 'high_altitude_bombing.png',
  33: 'it_has_a_child.png',
  34: 'jet_fighters.png',
  35: 'jets.png',
  36: 'made_in_a_lab.png',
  37: 'meta_morph.png',
  38: 'mimic.png',
  39: 'battery_monster.png',
  40: 'national_guard.png',
  41: 'nova_breath.png',
  42: 'nuclear_powerplant.png',
  43: 'detritivore.png',
  44: 'opportunist.png',
  45: 'parasitic_tentacles.png',
  46: 'plot_twist.png',
  47: 'poison_quills.png',
  48: 'poison_spit.png',
  49: 'psychic_probe.png',
  50: 'rapid_healing.png',
  51: 'regeneration.png',
  52: 'rooting_for_the_underdog.png',
  53: 'shrink_ray.png',
  54: 'skyscraper.png',
  55: 'smoke.png',
  56: 'solar_powered.png',
  57: 'spiked_tail.png',
  58: 'stretchy.png',
  59: 'tank.png',
  60: 'energy_drink.png',
  61: 'urbavore.png',
  62: 'vast_storm.png',
  63: 'were_only_making_it_stronger.png',
  64: 'wings.png',
};

export const CARDS: CardDef[] = CARD_DATA.map(card => ({
  ...card,
  imageUrl: getCardImage(IMAGE_FILES[card.id] ?? ''),
}));

export const CARD_MAP: Record<number, CardDef> = Object.fromEntries(
  CARDS.map(c => [c.id, c])
);
